---
title: "Subclustering the cells from the stimulation experiments"
output: html_notebook
---

```{r}
library(Seurat)
library(dplyr)
```

Load integrated object

```{r}
load("~/Dropbox/Zoe/scf_version/analysis/healthy_sc/seurat_objects/no_dropletQC/3391/integrated_3391_stimulation_pmaio_unstim_downsampled_cca_kanchor5_scClustViz.RData")
```

Set identities:

```{r}
Idents(scSeurat) <- "integrated_snn_res.0.4"
```

Sanity check with UMAPs:

```{r}
DimPlot(scSeurat, label = TRUE)
DimPlot(scSeurat, group.by = "tissue_type", label = FALSE)
DimPlot(scSeurat, group.by = "scina_labels", label = TRUE) & NoLegend()
```

# T cells

Isolate T-cells and scale.

```{r}
# Store metadata
scSeurat <- AddMetaData(scSeurat, 
                    Idents(scSeurat), 
                    col.name = "original_clusters_res.0.4")
tcells_sobj <- subset(scSeurat,
                      idents = c("2","6"))
DefaultAssay(tcells_sobj) <- "integrated"
# Recluster
tcells_sobj <- RunPCA(tcells_sobj) %>%
  FindNeighbors(dims = 1:30) %>%
  RunUMAP(dims = 1:30) %>%
  RunTSNE()
```

Cluster with scClustViz

```{r}
scSeurat <- tcells_sobj
DE_bw_clust <- TRUE
FDRthresh <- 0.01
seurat_resolution <- 0
sCVdata_list <- list()

while(seurat_resolution < 1.0) {
  seurat_resolution <- seurat_resolution + 0.2
  # ^ iteratively incrementing resolution parameter
  
  scSeurat <- FindClusters(scSeurat,
                           resolution=seurat_resolution,
                           print.output=F)
  message(" ")
  message("------------------------------------------------------")
  message(paste0("--------  res.",seurat_resolution," with ",
                 length(levels(Idents(scSeurat)))," clusters --------"))
  message("------------------------------------------------------")
  curr_sCVdata <- CalcSCV(inD=scSeurat,
                          cl=Idents(scSeurat),
                          # ^ your most recent clustering results get stored in the Seurat "ident" slot
                          assayType = "SCT",
                          exponent=exp(1),
                          pseudocount=1,
                          DRthresh=0.1,
                          DRforClust="pca",
                          calcSil=T,
                          calcDEvsRest=T,
                          calcDEcombn=T)
  
  DE_bw_NN <- sapply(DEneighb(curr_sCVdata,FDRthresh),nrow)
  # ^ counts # of DE genes between neighbouring clusters at your selected FDR threshold
  
  if (min(DE_bw_NN) < 1 | seurat_resolution > 2) { DE_bw_clust <- FALSE }
  # ^ If no DE genes between nearest neighbours, don't loop again.
  
  sCVdata_list[[paste0("res.",seurat_resolution)]] <- curr_sCVdata
}

DefaultAssay(scSeurat) <- "SCT"
```

Save

```{r}
save(sCVdata_list, scSeurat,
     file = "~/Dropbox/Zoe/scf_version/analysis/healthy_sc/seurat_objects/no_dropletQC/3391/integrated_3391_stimulation_pmaio_unstim_downsampled_cca_kanchor5_tcells_scClustViz.RData")
```

# Macrophages

Isolate macrophages and scale.

```{r}
# Store metadata
scSeurat <- AddMetaData(scSeurat, 
                    Idents(scSeurat), 
                    col.name = "original_clusters_res.0.4")
mac_sobj <- subset(scSeurat,
                      idents = c("1"))
DefaultAssay(mac_sobj) <- "integrated"
# Recluster
mac_sobj <- RunPCA(mac_sobj) %>%
  FindNeighbors(dims = 1:30) %>%
  RunUMAP(dims = 1:30) %>%
  RunTSNE()
```

Cluster with scClustViz

```{r}
scSeurat <- mac_sobj
DE_bw_clust <- TRUE
FDRthresh <- 0.01
seurat_resolution <- 0
sCVdata_list <- list()

while(seurat_resolution < 1.0) {
  seurat_resolution <- seurat_resolution + 0.2
  # ^ iteratively incrementing resolution parameter
  
  scSeurat <- FindClusters(scSeurat,
                           resolution=seurat_resolution,
                           print.output=F)
  message(" ")
  message("------------------------------------------------------")
  message(paste0("--------  res.",seurat_resolution," with ",
                 length(levels(Idents(scSeurat)))," clusters --------"))
  message("------------------------------------------------------")
  curr_sCVdata <- CalcSCV(inD=scSeurat,
                          cl=Idents(scSeurat),
                          # ^ your most recent clustering results get stored in the Seurat "ident" slot
                          assayType = "SCT",
                          exponent=exp(1),
                          pseudocount=1,
                          DRthresh=0.1,
                          DRforClust="pca",
                          calcSil=T,
                          calcDEvsRest=T,
                          calcDEcombn=T)
  
  DE_bw_NN <- sapply(DEneighb(curr_sCVdata,FDRthresh),nrow)
  # ^ counts # of DE genes between neighbouring clusters at your selected FDR threshold
  
  if (min(DE_bw_NN) < 1 | seurat_resolution > 2) { DE_bw_clust <- FALSE }
  # ^ If no DE genes between nearest neighbours, don't loop again.
  
  sCVdata_list[[paste0("res.",seurat_resolution)]] <- curr_sCVdata
}

DefaultAssay(scSeurat) <- "SCT"
```

Save

```{r}
save(sCVdata_list, scSeurat,
     file = "~/Dropbox/Zoe/scf_version/analysis/healthy_sc/seurat_objects/no_dropletQC/3391/integrated_3391_stimulation_pmaio_unstim_downsampled_cca_kanchor5_mac_scClustViz.RData")
```


